
  CREATE TABLE "APUSER"."TB_ORDER" 
   (	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HOSTER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ORDER_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"ORDER_TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"STORE_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONTACT_METHOD" VARCHAR2(100 BYTE), 
	"AMOUNT_LIMIT" NUMBER, 
	"STATUS" VARCHAR2(30 BYTE), 
	 CONSTRAINT "TB_ORDER_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "APUSER"."TB_ORDER"."CREATE_TIME" IS '資料建立時間';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."UPDATE_TIME" IS '資料異動時間';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."ORDER_ID" IS '訂單ID';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."HOSTER_ID" IS '主辦人ID, REF TB_USER.USER_ID';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."ORDER_DATE" IS '訂單開始時間';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."END_DATE" IS '訂單結束時間';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."ORDER_TYPE" IS '訂單類型';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."STORE_ID" IS '店家ID';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."CONTACT_METHOD" IS '聯絡方式';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."AMOUNT_LIMIT" IS '限制人數';
   COMMENT ON COLUMN "APUSER"."TB_ORDER"."STATUS" IS '訂單狀態';
   COMMENT ON TABLE "APUSER"."TB_ORDER"  IS '訂單資料';
