
  CREATE TABLE "APUSER"."TB_USER" 
   (	"CREATR_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"USER_NM" NVARCHAR2(50) NOT NULL ENABLE, 
	"GENRDER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"AGE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(50 BYTE), 
	 CONSTRAINT "TB_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "APUSER"."TB_USER"."CREATR_TIME" IS '資料建立時間';
   COMMENT ON COLUMN "APUSER"."TB_USER"."UPDATE_TIME" IS '資料異動時間';
   COMMENT ON COLUMN "APUSER"."TB_USER"."USER_ID" IS '使用者ID';
   COMMENT ON COLUMN "APUSER"."TB_USER"."USER_NM" IS '使用者名稱';
   COMMENT ON COLUMN "APUSER"."TB_USER"."GENRDER" IS '性別';
   COMMENT ON COLUMN "APUSER"."TB_USER"."AGE" IS '年紀';
   COMMENT ON COLUMN "APUSER"."TB_USER"."MAIL" IS '信箱';
   COMMENT ON TABLE "APUSER"."TB_USER"  IS '使用者資料';

