CREATE OR REPLACE NONEDITIONABLE PACKAGE APUSER.PG_ORDER AS 

    -- 訂單資料
    TYPE TO_ORDER_INFO IS RECORD(
        ORDER_ID APUSER.TB_ORDER.ORDER_ID%TYPE,
        HOSTER_ID APUSER.TB_ORDER.HOSTER_ID%TYPE,
        ORDER_DATE APUSER.TB_ORDER.ORDER_DATE%TYPE,
        END_DATE APUSER.TB_ORDER.END_DATE%TYPE,
        ORDER_TYPE APUSER.TB_ORDER.ORDER_TYPE%TYPE,
        STORE_ID APUSER.TB_ORDER.STORE_ID%TYPE,
        CONTACT_METHOD APUSER.TB_ORDER.CONTACT_METHOD%TYPE,
        AMOUNT_LIMIT APUSER.TB_ORDER.AMOUNT_LIMIT%TYPE,
        STATUS APUSER.TB_ORDER.STATUS%TYPE
    );
    
    -- 訂單資料清單
    TYPE TT_ORDER_INFO_LIST IS TABLE OF TO_ORDER_INFO;

  FUNCTION FN_UPSERT_ORDER(
    I_ORDER_ID APUSER.TB_ORDER.ORDER_ID%TYPE,
    I_HOSTER_ID APUSER.TB_ORDER.HOSTER_ID%TYPE,
    I_ORDER_DATE APUSER.TB_ORDER.ORDER_DATE%TYPE,
    I_END_DATE APUSER.TB_ORDER.END_DATE%TYPE,
    I_ORDER_TYPE APUSER.TB_ORDER.ORDER_TYPE%TYPE,
    I_STORE_ID APUSER.TB_ORDER.STORE_ID%TYPE,
    I_CONTACT_METHOD APUSER.TB_ORDER.CONTACT_METHOD%TYPE,
    I_AMOUNT_LIMIT APUSER.TB_ORDER.AMOUNT_LIMIT%TYPE,
    I_STATUS APUSER.TB_ORDER.STATUS%TYPE
  ) RETURN NUMBER;
  
  FUNCTION FN_GET_ORDER(
    I_ORDER_ID APUSER.TB_ORDER.ORDER_ID%TYPE
  )RETURN SYS_REFCURSOR;
  
  PROCEDURE SP_QRY_ORDERS(
    I_ORDER_ID APUSER.TB_ORDER.ORDER_ID%TYPE,
    I_HOSTER_ID APUSER.TB_ORDER.HOSTER_ID%TYPE,
    I_ORDER_DATE APUSER.TB_ORDER.ORDER_DATE%TYPE,
    I_END_DATE APUSER.TB_ORDER.END_DATE%TYPE,
    I_ORDER_TYPE APUSER.TB_ORDER.ORDER_TYPE%TYPE,
    I_STORE_ID APUSER.TB_ORDER.STORE_ID%TYPE,
    I_CONTACT_METHOD APUSER.TB_ORDER.CONTACT_METHOD%TYPE,
    I_AMOUNT_LIMIT APUSER.TB_ORDER.AMOUNT_LIMIT%TYPE,
    I_STATUS APUSER.TB_ORDER.STATUS%TYPE,
    I_PAGE_NO NUMBER,
    I_PAGE_SIZE NUMBER,
    O_TOTAL OUT NUMBER,
    O_RESULT OUT SYS_REFCURSOR
  );

END PG_ORDER;