CREATE OR REPLACE NONEDITIONABLE PACKAGE APUSER.PG_USER AS 
    
    -- 使用者資料
    TYPE TO_USER_INFO IS RECORD(
        CREATR_TIME APUSER.TB_USER.CREATR_TIME%TYPE, 
        UPDATE_TIME APUSER.TB_USER.UPDATE_TIME%TYPE, 
        USER_ID APUSER.TB_USER.USER_ID%TYPE, 
        USER_NM APUSER.TB_USER.USER_NM%TYPE, 
        GENRDER APUSER.TB_USER.GENRDER%TYPE, 
        AGE APUSER.TB_USER.AGE%TYPE, 
        MAIL APUSER.TB_USER.MAIL%TYPE
    );
    
    -- 使用者資料清單
    TYPE TT_USER_INFO_LIST IS TABLE OF TO_USER_INFO;
    
    -- 取得使用者資訊
    FUNCTION FN_GET_USER_INFO(
        I_USER_ID VARCHAR2,
        I_USER_NM VARCHAR2,
        I_GENRDER VARCHAR2
    ) RETURN SYS_REFCURSOR;

END PG_USER;